version: '3'
services:
  dev:
    image: node:11
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: >
      sh -c "cp -n .env.example .env &&
          npm run ${ENV:-dev}"
    ports:
      - ${PORT:-3000}:${PORT:-3000}